services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usersdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-service:
    build:
      context: .
      dockerfile: Services/UserService/UserService.API/Dockerfile
    image: sanjhi.user.api
    container_name: sanjhi.user.api
    ports:
      - "8002:80"
      - "8003:443"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Password: reallyStrongPassword123
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    depends_on:
      - postgres
    volumes:
      - ${HOME}/.aspnet/dev-certs/https:/https/
    healthcheck:
      test: [ "CMD", "curl", "-f", "https://localhost:443/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
